[package]
name = "aoraki"
version = "0.1.0"
authors = ["nabeen <watanabe_kenichiro@hasigo.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { version = "0.14.3", features = ["std_web"] }
